### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by cosmitir** [relative/synchrony#122]
Obfuscated Javascript: [zmq.zip](https://github.com/relative/synchrony/files/11827904/zmq.zip)

Terminal Output:

```
PS C:\Users\idgr2\AppData\Local\Programs\GaneshBot\resources\app> synchrony deobfuscate .\electrondist\zmq.js  
Running Simplify transformer
Running MemberExpressionCleaner transformer
Running LiteralMap transformer
Running DeadCode transformer
Running Demangle transformer
Running StringDecoder transformer
Caught an error while attempting to run AST visitor!

node = Node {
  type: 'ExpressionStatement',
  start: 561,
  end: 1106,
  range: [ 561, 1106 ],
  expression: Node {
    type: 'CallExpression',
    start: 562,
    end: 1104,
    range: [ 562, 1104 ],
    callee: Node {
      type: 'FunctionExpression',
      start: 562,
      end: 1084,
      range: [Array],
      id: null,
      expression: false,
      generator: false,
      async: false,
      params: [Array],
      body: [Node]
    },
    arguments: [ [Node], [Node] ],
    optional: false
  }
}
err = Error: Failed to find string array with identifier "a14_0x4740" for push/shift calc
    at t (C:\Users\idgr2\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:23401)
    at ExpressionStatement (C:\Users\idgr2\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:23825)
    at s (C:\Users\idgr2\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:147)
    at Object.skipThrough (C:\Users\idgr2\AppData\Roaming\npm\node_modules\deobfuscator\node_modules\acorn-walk\dist\walk.js:186:39)
    at s (C:\Users\idgr2\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:133)
    at base.Program.base.BlockStatement.base.StaticBlock (C:\Users\idgr2\AppData\Roaming\npm\node_modules\deobfuscator\node_modules\acorn-walk\dist\walk.js:198:7)
    at s (C:\Users\idgr2\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:133)
    at m (C:\Users\idgr2\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:22)
    at ge.shiftFinder (C:\Users\idgr2\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:23584)
    at ge.<anonymous> (C:\Users\idgr2\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:28349)
shifted = 0 arrays = 0
Running Simplify transformer
Running MemberExpressionCleaner transformer
Running Desequence transformer
Running ControlFlow transformer
Running Desequence transformer
Running MemberExpressionCleaner transformer
Running Simplify transformer
Running DeadCode transformer
Running Simplify transformer
Running DeadCode transformer
```

**Comment by relative** [comment]
find a sample from non commercial software and open a new ticket
