### ISSUE TITLE
Cannot Read Property

### ISSUE THREAD

**Issue by bbday** [relative/synchrony#13]
With last update i have this issue (i tried to disable also ll modules, look like is comming from StringDecoderTransformer):
(6/6) executing BufferCleanerTransformer
Deobfuscation failed TypeError: Cannot read property '1' of undefined
    at CallExpression (D:\jsDeob\src\transformers\StringDecoder.js:317:46)
    at c (D:\jsDeob\node_modules\acorn-walk\dist\walk.js:30:20)
    at Object.skipThrough (D:\jsDeob\node_modules\acorn-walk\dist\walk.js:186:39)
    at c (D:\jsDeob\node_modules\acorn-walk\dist\walk.js:29:24)
    at Object.base.NewExpression.base.CallExpression (D:\jsDeob\node_modules\acorn-walk\dist\walk.js:395:11)
    at c (D:\jsDeob\node_modules\acorn-walk\dist\walk.js:29:24)
    at Object.skipThrough (D:\fifaup\jsDeob\node_modules\acorn-walk\dist\walk.js:186:39)
    at c (D:\jsDeob\node_modules\acorn-walk\dist\walk.js:29:24)
    at Object.base.BinaryExpression.base.LogicalExpression (D:\jsDeob\node_modules\acorn-walk\dist\walk.js:376:5)
    at c (D:\jsDeob\node_modules\acorn-walk\dist\walk.js:29:24)

**Comment by relative** [comment]
Can you provide the file you tried deobfuscating and the config you used
