### ISSUE TITLE
Caught an error while attempting to run AST visitor!

### ISSUE THREAD

**Issue by youdie323323** [relative/synchrony#134]
Caught an error while attempting to run AST visitor!

node = Node {
  type: 'IfStatement',
  start: 20184,
  end: 21604,
  range: [ 20184, 21604 ],
  test: Node {
    type: 'BinaryExpression',
    start: 20187,
    end: 20194,
    range: [ 20187, 20194 ],
    left: Node {
      type: 'Identifier',
      start: 20187,
      end: 20188,
      range: [Array],
      name: 't'
    },
    operator: '===',
    right: Node {
      type: 'Literal',
      start: 20191,
      end: 20194,
      range: [Array],
      value: 208,
      raw: '208'
    }
  },
  consequent: Node {
    type: 'BlockStatement',
    start: 20195,
    end: 20211,
    range: [ 20195, 20211 ],
    expression: Node {
      type: 'AssignmentExpression',
      start: 20195,
      end: 20210,
      range: [Array],
      operator: '=',
      left: [Node],
      right: [Node]
    },
    body: [ [Object] ]
  },
  alternate: Node {
    type: 'IfStatement',
    start: 20216,
    end: 21604,
    range: [ 20216, 21604 ],
    test: Node {
      type: 'BinaryExpression',
      start: 20219,
      end: 20226,
      range: [Array],
      left: [Node],
      operator: '===',
      right: [Node]
    },
    consequent: Node {
      type: 'BlockStatement',
      start: 20227,
      end: 20244,
      range: [Array],
      expression: [Node],
      body: [Array]
    },
    alternate: Node {
      type: 'IfStatement',
      start: 20249,
      end: 21604,
      range: [Array],
      test: [Node],
      consequent: [Node],
      alternate: [Node]
    }
  }
}
err = RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at M (C:\Users\user\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:1664)
    at IfStatement (C:\Users\user\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:12557)
    at o (C:\Users\user\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:147)
    at Object.skipThrough (C:\Users\user\AppData\Roaming\npm\node_modules\deobfuscator\node_modules\acorn-walk\dist\walk.js:186:39)
    at o (C:\Users\user\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:133)
    at base.IfStatement (C:\Users\user\AppData\Roaming\npm\node_modules\deobfuscator\node_modules\acorn-walk\dist\walk.js:208:27)
    at o (C:\Users\user\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:133)
    at Object.skipThrough (C:\Users\user\AppData\Roaming\npm\node_modules\deobfuscator\node_modules\acorn-walk\dist\walk.js:186:39)
    at o (C:\Users\user\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:133)
    
    file: `https://cdn.discordapp.com/attachments/1170534081918930946/1183499297535295508/real.js`

**Comment by pabx06** [comment]
same issue here 
fix:[change helper functions immutate to](https://github.com/relative/synchrony/pull/136)
