### ISSUE TITLE
Error: UnaryExpression argument is not Literal

### ISSUE THREAD

**Issue by eliasto** [relative/synchrony#17]
Hello!

I have an error with the latest version. I just use `synchrony deobfuscator ./file.js`.

**The code:** https://pastebin.com/VSa39hag

**The error:**

<details>
<summary>Log output</summary>

```
Running Simplify transformer
Running MemberExpressionCleaner transformer
Running LiteralMap transformer
Running StringDecoder transformer
Caught an error while attempting to run AST visitor!

node = Node {
  type: 'CallExpression',
  start: 9973,
  end: 10014,
  callee: Node { type: 'Identifier', start: 9973, end: 9975, name: 'EF' },
  arguments: [
    Node {
      type: 'UnaryExpression',
      start: 9976,
      end: 9989,
      operator: 'typeof',
      prefix: true,
      argument: [Node]
    },
    Node {
      type: 'CallExpression',
      start: 9990,
      end: 10013,
      callee: [Node],
      arguments: [Array],
      optional: false
    }
  ],
  optional: false
}
err = TypeError: UnaryExpression argument is not Literal
    at j (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:8407)
    at W (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:8754)
    at C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:12664
    at Array.map (<anonymous>)
    at literals_to_arg_array (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:12652)
    at CallExpression (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:21581)
    at p (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:147)
    at Object.skipThrough (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\node_modules\acorn-walk\dist\walk.js:186:39)
    at p (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:133)
    at Object.base.BinaryExpression.base.LogicalExpression (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\node_modules\acorn-walk\dist\walk.js:376:5)
Caught an error while attempting to run AST visitor!

node = Node {
  type: 'CallExpression',
  start: 15527,
  end: 15578,
  callee: Node { type: 'Identifier', start: 15527, end: 15529, name: 'EF' },
  arguments: [
    Node {
      type: 'UnaryExpression',
      start: 15530,
      end: 15555,
      operator: 'typeof',
      prefix: true,
      argument: [Node]
    },
    Node {
      type: 'CallExpression',
      start: 15556,
      end: 15577,
      callee: [Node],
      arguments: [Array],
      optional: false
    }
  ],
  optional: false
}
err = TypeError: UnaryExpression argument is not Literal
    at j (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:8407)
    at W (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:8754)
    at C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:12664
    at Array.map (<anonymous>)
    at literals_to_arg_array (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:12652)
    at CallExpression (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:21581)
    at p (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:147)
    at Object.skipThrough (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\node_modules\acorn-walk\dist\walk.js:186:39)
    at p (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:133)
    at Object.base.IfStatement (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\node_modules\acorn-walk\dist\walk.js:206:5)
Caught an error while attempting to run AST visitor!

node = Node {
  type: 'CallExpression',
  start: 95980,
  end: 96017,
  callee: Node { type: 'Identifier', start: 95980, end: 95982, name: 'EF' },
  arguments: [
    Node {
      type: 'UnaryExpression',
      start: 95983,
      end: 95992,
      operator: 'typeof',
      prefix: true,
      argument: [Node]
    },
    Node {
      type: 'CallExpression',
      start: 95993,
      end: 96016,
      callee: [Node],
      arguments: [Array],
      optional: false
    }
  ],
  optional: false
}
err = TypeError: UnaryExpression argument is not Literal
    at j (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:8407)
    at W (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:8754)
    at C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:12664
    at Array.map (<anonymous>)
    at literals_to_arg_array (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:12652)
    at CallExpression (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:21581)
    at p (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:147)
    at Object.skipThrough (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\node_modules\acorn-walk\dist\walk.js:186:39)
    at p (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:133)
    at Object.base.ConditionalExpression (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\node_modules\acorn-walk\dist\walk.js:384:5)  
Caught an error while attempting to run AST visitor!

node = Node {
  type: 'CallExpression',
  start: 96130,
  end: 96171,
  callee: Node { type: 'Identifier', start: 96130, end: 96132, name: 'pW' },
  arguments: [
    Node {
      type: 'UnaryExpression',
      start: 96133,
      end: 96146,
      operator: 'typeof',
      prefix: true,
      argument: [Node]
    },
    Node {
      type: 'CallExpression',
      start: 96147,
      end: 96170,
      callee: [Node],
      arguments: [Array],
      optional: false
    }
  ],
  optional: false
}
err = TypeError: UnaryExpression argument is not Literal
    at j (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:8407)
    at W (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:8754)
    at C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:12664
    at Array.map (<anonymous>)
    at literals_to_arg_array (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:12652)
    at CallExpression (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:21581)
    at p (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:147)
    at Object.skipThrough (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\node_modules\acorn-walk\dist\walk.js:186:39)
    at p (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:133)
    at Object.base.IfStatement (C:\Users\elias\AppData\Roaming\npm\node_modules\deobfuscator\node_modules\acorn-walk\dist\walk.js:206:5)
Running Simplify transformer
Running MemberExpressionCleaner transformer
Running Desequence transformer
Running ControlFlow transformer
s7.z3 = FunctionExpression
s7.TC = FunctionExpression
s7.G7 = Identifier
s7.G7 = Identifier
s7.jG = Identifier
s7.jG = Identifier
s7.G7 = Identifier
s7.G7 = Identifier
s7.jG = Identifier
s7.jG = Identifier
s7.G7 = Identifier
s7.G7 = Identifier
s7.jG = Identifier
s7.jG = Identifier
Running Desequence transformer
Running MemberExpressionCleaner transformer
Running Simplify transformer
Running DeadCode transformer
```

</details>
Thank you for your help!

**Comment by relative** [comment]
script doesn't appear to be javascript-obfuscator and it appears to be broken (non-ascii bytes). 

  is the script supposed to have non ASCII characters in it?
