### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:25261)

### ISSUE THREAD

**Issue by G6KG** [relative/synchrony#20]
trying to deobfuscate : https://github.com/asicanloveyou/RAGNAROK/blob/main/SCYLLA.js

Error :

/opt/homebrew/lib/node_modules/deobfuscator/node_modules/acorn/dist/acorn.js:3460
    var err = new SyntaxError(message);
              ^

SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:25261)
    at Parser.pp$4.raise (/opt/homebrew/lib/node_modules/deobfuscator/node_modules/acorn/dist/acorn.js:3460:15)
    at Parser.pp$8.parseStatement (/opt/homebrew/lib/node_modules/deobfuscator/node_modules/acorn/dist/acorn.js:930:18)
    at Parser.pp$8.parseTopLevel (/opt/homebrew/lib/node_modules/deobfuscator/node_modules/acorn/dist/acorn.js:813:23)
    at Parser.parse (/opt/homebrew/lib/node_modules/deobfuscator/node_modules/acorn/dist/acorn.js:586:17)
    at Function.parse (/opt/homebrew/lib/node_modules/deobfuscator/node_modules/acorn/dist/acorn.js:636:37)
    at Object.parse (/opt/homebrew/lib/node_modules/deobfuscator/node_modules/acorn/dist/acorn.js:5576:19)
    at ge.<anonymous> (/opt/homebrew/lib/node_modules/deobfuscator/dist/index.js:28:49736)
    at Generator.next (<anonymous>)
    at /opt/homebrew/lib/node_modules/deobfuscator/dist/index.js:1:1260
    at new Promise (<anonymous>) {
  pos: 25261,
  loc: Position { line: 1, column: 25261 },
  raisedAt: 25267
}

**Comment by G6KG** [comment]
➜  synchrony-git git:(master) ✗ synchrony --sourceType module -o script.cleaned.js Hades1.js
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AssertionError [ERR_ASSERTION]: ImportDeclaration should appear when the mode is ES6 and in the module context.
    at Referencer.ImportDeclaration (/Users/mac/synchrony-git/node_modules/eslint-scope/dist/eslint-scope.cjs:2065:35)
    at Referencer.Visitor.visit (/Users/mac/synchrony-git/node_modules/esrecurse/esrecurse.js:104:34)
    at Referencer.Visitor.visitChildren (/Users/mac/synchrony-git/node_modules/esrecurse/esrecurse.js:83:38)
    at Referencer.Program (/Users/mac/synchrony-git/node_modules/eslint-scope/dist/eslint-scope.cjs:1890:14)
    at Referencer.Visitor.visit (/Users/mac/synchrony-git/node_modules/esrecurse/esrecurse.js:104:34)
    at Object.analyze (/Users/mac/synchrony-git/node_modules/eslint-scope/dist/eslint-scope.cjs:2222:16)
    at new oe (/Users/mac/synchrony-git/dist/index.js:28:60118)
    at ke.<anonymous> (/Users/mac/synchrony-git/dist/index.js:28:61730)
    at Generator.next (<anonymous>)
    at /Users/mac/synchrony-git/dist/index.js:1:1267 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

Node.js v17.8.0

**Comment by relative** [comment]
fixed
