### ISSUE TITLE
ERROR: Caught an error while attempting to run AST visitor!

### ISSUE THREAD

**Issue by klefo0** [relative/synchrony#58]
- Version: 2.4.1
- Output: 
```
Caught an error while attempting to run AST visitor!

node = Node {
  type: 'ExpressionStatement',
  start: 6313,
  end: 17304,
  range: [ 6313, 17304 ],
  expression: Node {
    type: 'SequenceExpression',
    start: 6314,
    end: 17302,
    range: [ 6314, 17302 ],
    expressions: [ [Node], [Node] ]
  }
}
err = Error: Failed to find string array with identifier "_0x777b" for push/shift calc
    at t (C:\Users\Klefo\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:23401)
    at ExpressionStatement (C:\Users\Klefo\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:23683)
    at s (C:\Users\Klefo\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:147)
    at Object.skipThrough (C:\Users\Klefo\AppData\Roaming\npm\node_modules\deobfuscator\node_modules\acorn-walk\dist\walk.js:186:39)
    at s (C:\Users\Klefo\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:133)
    at Object.base.Program.base.BlockStatement.base.StaticBlock

 (C:\Users\Klefo\AppData\Roaming\npm\node_modules\deobfuscator\node_modules\acorn-walk\dist\walk.js:198:7)
    at s (C:\Users\Klefo\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:25:133)
    at m (C:\Users\Klefo\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:22)
    at ge.shiftFinder (C:\Users\Klefo\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:23584)
    at ge.<anonymous> (C:\Users\Klefo\AppData\Roaming\npm\node_modules\deobfuscator\dist\index.js:28:28349)
```
- Input: [handleCommand.txt](https://github.com/relative/synchrony/files/11114184/handleCommand.txt)

**Comment by iamkhalidbashir** [comment]
same
